from __future__ import annotations

PIPELINE_VERSION = "2"
DEFAULT_MAX_DURATION_S = 1_800
MAX_CONFIGURABLE_DURATION_S = 14_400
DEFAULT_TRANSCRIPT_LIMIT = 40
MAX_TRANSCRIPT_LIMIT = 200
DEFAULT_MOMENT_LIMIT = 20
MAX_MOMENT_LIMIT = 100
DEFAULT_SEARCH_LIMIT = 10
MAX_SEARCH_LIMIT = 50
FRAME_SAMPLE_FPS = 1.0
MAX_ANALYSIS_FRAME_EDGE = 1_920
MAX_SOURCE_FRAME_EDGE = 8_192
MAX_SOURCE_FRAME_PIXELS = 33_554_432
PHASH_DISTANCE_THRESHOLD = 8
MIN_STABLE_SECONDS = 2.0
VISUAL_PROBE_CHAPTER_CANDIDATES = 8
VISUAL_PROBE_UNIFORM_CANDIDATES = 16
VISUAL_PROBE_MAX_MOMENTS = 12
VISUAL_PROBE_MAX_EDGE = 960
MAX_IMAGE_EDGE = 1_600
MAX_IMAGE_BYTES = 2_000_000

SUPPORTED_VIDEO_EXTENSIONS = {
    ".avi",
    ".m4v",
    ".mkv",
    ".mov",
    ".mp4",
    ".mpeg",
    ".mpg",
    ".webm",
}
